changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Tests
      labels:
        - test
        - testing
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Other Changes
      labels:
        - '*'
